string-manipulation-3 Challenge - Sang Tran
Stran1025/c0322-code-solutions pull request #53
Opened 2022-03-30 19:54 UTC by Stran1025

2022-03-30 19:54 UTC, Stran1025 commented
![screencapture-127-0-0-1-5500-string-manipulation-3-index-html-2022-03-30-12_52_56](https://user-images.githubusercontent.com/97194085/160919682-dabb50b6-585c-4b77-ad8d-020613603869.png)

2022-03-30 21:47 UTC, codingcodymiller requested changes

2022-03-30 21:47 UTC, codingcodymiller commented on string-manipulation-3/src/is-anagram.js
> +      array1.pop();
Why `pop`? Wouldn't you want to remove this specific space character?

2022-03-30 21:47 UTC, codingcodymiller commented on string-manipulation-3/src/title-case.js
> +      if (array[i] === 'javascript:') {
Why does this check only happen for the first word? What if the title was "Adventures in JavaScript: Living By A Code"?

2022-04-01 16:36 UTC, codingcodymiller approved these changes
Nice work!!

2022-04-01 16:50 UTC, merged